spring:
  application:
    name: mine-game
  profiles:
    active: @package.environment@
server:
  port: 6103

#游戏配置###########################################################################################################################

#奖励
#value: 类型, 未知(0), 金币(1), 钻石(2), 无限币(3)
#name: 名称
#amount: 奖励总数
#单位: 分
#level: 奖品级别,同类型奖励不允许出现相同的级别

#1.未知######
game:
  award-type-list:
    - &award-type-list-0
      value: 0
      name: 未知
      amount: 0
      level: 0
#2.金币######
    - &award-type-gold-coin-1
      value: 1
      name: 1金币
      amount: 10
      level: 0
    - &award-type-gold-coin-3
      value: 1
      name: 3金币
      amount: 30
      level: 0
    - &award-type-gold-coin-6
      value: 1
      name: 6金币
      amount: 60
      level: 0
    - &award-type-gold-coin-10
      value: 1
      name: 小金币
      amount: 100
      level: 0
    - &award-type-gold-coin-50
      value: 1
      name: 中金币
      amount: 500
      level: 0
    - &award-type-gold-coin-100
      value: 1
      name: 大金币
      amount: 1000
      level: 0
#3.钻石######
    - &award-type-list-4
      value: 2
      name: 小钻石
      amount: 10
      level: 0
    - &award-type-list-5
      value: 2
      name: 中钻石
      amount: 50
      level: 1
    - &award-type-list-6
      value: 2
      name: 大钻石
      amount: 200
      level: 2
#3.无限币######
    - &award-type-list-7
      value: 3
      name: 小无限币
      amount: 0
      level: 0
    - &award-type-list-8
      value: 3
      name: 大无限币
      amount: 0
      level: 1
#4.经验######
    - &award-type-list-exp-1
      value: 4
      name: 经验
      amount: 1
      level: 0
#5.体力######
    - &award-type-list-energy-1
      value: 5
      name: 体力
      amount: 1
      level: 0
#6.宝箱######
    - &award-type-list-bao-xiang-1
      value: 6
      name: 宝箱
      amount: 1
      level: 0

#######################################################################
#地块                                                                 #
#type: 地块(0), 障碍(1), 金币(2), 钻石(3), 无限币(4) ---> 大类别          #
#subType: --------> 子类,同一type下, subType不同                        #
#name: 名称                                                           #
#spendTimeInSecond: 挖掘时间(单位: 秒)                                  #
#consumeEnergy: 消耗体力                                               #
#exp 经验                                                             #
#####################################################################

#1.地块######

  #土块
  land-area-config:
    size-of-page-land-area: 301
    land-area-type-config-list:
      - total-list: [2524,140,60,30,20]
        landAreaType: &land-area-type-0
          type: 0
          subType: 1
          name: 土块
          spendTimeInSecond: 5
          consumeEnergy: 1
          exp: 1
          awardType:
            *award-type-gold-coin-1
  #石土混合
      - total-list: [797,50,50,50,20]
        landAreaType: &land-area-type-1
          type: 0
          subType: 2
          name: 石土混合
          spendTimeInSecond: 20
          consumeEnergy: 1
          exp: 1
          awardType:
            *award-type-gold-coin-6
  #石块
      - total-list: [1595,80,70,30,20]
        landAreaType: &land-area-type-2
          type: 0
          subType: 3
          name: 石块
          spendTimeInSecond: 10
          consumeEnergy: 1
          exp: 1
          awardType:
            *award-type-gold-coin-3

  #2.障碍######

  #冒烟土地
      - total-list: [199,10,10,0,0]
        landAreaType: &land-area-type-buff-1
          type: 1
          subType: 101
          name: 冒烟土地
          spendTimeInSecond: 60
          consumeEnergy: 0
          exp: 0
          awardType:
            *award-type-list-0
  #水洼
      - total-list: [199,10,10,10,0]
        landAreaType: &land-area-type-buff-2
          type: 1
          subType: 102
          name: 水洼
          spendTimeInSecond: 0
          consumeEnergy: 0
          exp: 0
          awardType:
            *award-type-list-0
  #地底植物
      - total-list: [199,10,10,10,0]
        landAreaType: &land-area-type-buff-3
          type: 1
          subType: 103
          name: 地底植物
          spendTimeInSecond: 0
          consumeEnergy: 0
          exp: 0
          awardType:
            *award-type-list-0
  #老鼠
      - total-list: [5,10,10,10,0]
        landAreaType: &land-area-type-buff-4
          type: 1
          subType: 104
          name: 老鼠
          spendTimeInSecond: 0
          consumeEnergy: 0
          exp: 0
          awardType:
            *award-type-list-0
  #宝箱
      - total-list: [50,10,10,10,0]
        landAreaType: &land-area-type-buff-5
          type: 1
          subType: 105
          name: 宝箱
          spendTimeInSecond: 0
          consumeEnergy: 0
          exp: 0
          awardType:
            *award-type-list-bao-xiang-1
  #3.金币矿######

  #一袋金币
      - total-list: [199,30,20,20,20]
        landAreaType: &land-area-type-6
          type: 2
          subType: 201
          name: 一袋金币
          spendTimeInSecond: 50
          consumeEnergy: 1
          exp: 1
          awardType:
            *award-type-gold-coin-10
  #一堆金币
      - total-list: [100,30,30,30,20]
        landAreaType: &land-area-type-7
          type: 2
          subType: 202
          name: 一堆金币
          spendTimeInSecond: 80
          consumeEnergy: 1
          exp: 1
          awardType:
            *award-type-gold-coin-50
  #一箱金币
      - total-list: [60,20,20,20,20]
        landAreaType: &land-area-type-8
          type: 2
          subType: 203
          name: 一箱金币
          spendTimeInSecond: 100
          consumeEnergy: 1
          exp: 1
          awardType:
            *award-type-gold-coin-100

  #3.钻石矿######

  #一颗钻石
      - total-list: [8,50,70,50,30]
        landAreaType: &land-area-type-9
          type: 3
          subType: 301
          name: 一颗钻石
          spendTimeInSecond: 100
          consumeEnergy: 1
          exp: 1
          awardType:
            *award-type-list-4
  #一袋钻石
      - total-list: [2,20,100,170,190]
        landAreaType: &land-area-type-10
          type: 3
          subType: 302
          name: 一袋钻石
          spendTimeInSecond: 180
          consumeEnergy: 1
          exp: 1
          awardType:
            *award-type-list-5
  #蓝宝石矿
      - total-list: [1,0,0,30,110]
        landAreaType: &land-area-type-11
          type: 3
          subType: 303
          name: 蓝宝石矿
          spendTimeInSecond: 210
          consumeEnergy: 1
          exp: 1
          awardType:
            *award-type-list-6
  #4.无限币矿######

  #一枚无限币
      - total-list: [11,30,30,30,30]
        landAreaType: &land-area-type-12
          type: 4
          subType: 401
          name: 一枚无限币
          spendTimeInSecond: 350
          consumeEnergy: 1
          exp: 1
          awardType:
            *award-type-list-7
  #紫水晶矿
      - total-list: [6,20,20,20,20]
        landAreaType: &land-area-type-13
          type: 4
          subType: 402
          name: 紫水晶矿
          spendTimeInSecond: 470
          consumeEnergy: 1
          exp: 1
          awardType:
            *award-type-list-8

#VR币配置(单位:元,角),配置单位为角

#1.无限币上限######
  vr-coin-config:
    max: 210000000
#2.无限币掉落天数######
    base-day-count: 18250
#3.玩家基数######
    base-player-count: 800
#3.无限币开放开始时间######
    start-time: 1501430400000
#3.无限币随机配置######
#无限币小
    subtype-random-config:
      - [16,17,18,19,20]
#无限币大
      - [32,34,36,38,40]

#体力配置
#1.最大体力######
  energy-config:
    max: 200
#2.恢复单位体力所需时间(时间单位: 分钟)######
    time-in-second-increase-unit-energy: 120
#3.用户每天可购买体力最大值######
    user-buy-max-energy-each-day: 300
#4.每时间段领取体力最大值######
    max-receive-energy-in-each-time-range: 100
#设置每日体力(可设置多个时间段)######
  receive-energy-list:
    - num: 1
      startTime: '09:00:00'
      endTime: '11:00:00'
    - num: 2
      startTime: '15:00:00'
      endTime: '19:00:00'

