spring:
  data:
    mongodb:
      uri: mongodb://mine:123456@1.mongodb.db:22000,2.mongodb.db:22000,3.mongodb.db:22000/mine
  redis:
    cluster:
      nodes: redis.cloud.server1:6381,redis.cloud.server2:6381,redis.cloud.server3:6381,redis.cloud.server4:6382,redis.cloud.server5:6382,redis.cloud.server4:6382

application:
  vr-coin-redis-key: game-vr-coin-remain
  dubbo:
    applicationName: wxsk_vr_mine_game
    registryAddress: zookeeper://com.wxsk.vr.shop.zookeeper1:2181?backup=com.wxsk.vr.shop.zookeeper1:2181,com.wxsk.vr.shop.zookeeper1:2181
    port: 60003

logging:
  config: classpath:log4j2.xml

#游戏配置###########################################################################################################################

#奖励
#value: 类型, 未知(0), 金币(1), 钻石(2), 无限币(3)
#name: 名称
#amount: 奖励总数
#level: 奖品级别,同类型奖励不允许出现相同的级别

#1.未知######
game:
  award-type-list:
    - &award-type-list-0
      value: 0
      name: 未知
      amount: 0
      level: 0
#2.金币######
    - &award-type-list-1
      value: 1
      name: 小金币
      amount: 100
      level: 0
    - &award-type-list-2
      value: 1
      name: 中金币
      amount: 200
      level: 1
    - &award-type-list-3
      value: 1
      name: 大金币
      amount: 300
      level: 2
#3.钻石######
    - &award-type-list-4
      value: 2
      name: 小钻石
      amount: 5
      level: 0
    - &award-type-list-5
      value: 2
      name: 中钻石
      amount: 20
      level: 1
    - &award-type-list-6
      value: 2
      name: 大钻石
      amount: 50
      level: 2
#3.无限币######
    - &award-type-list-7
      value: 3
      name: 小无限币
      amount: 0
      level: 0
    - &award-type-list-8
      value: 3
      name: 大无限币
      amount: 0
      level: 1

#地块
#type: 地块(0), 障碍(1), 金币(2), 钻石(3), 无限币(4) ---> 大类别
#subType: --------> 子类,同一type下, subType不同
#name: 名称
#spendTimeInSecond: 挖掘时间(单位: 秒)
#consumeEnergy: 消耗体力

#1.地块######

#土块
  land-area-type-config-list:
    - total-list: [14,14,6,3,2]
      landAreaType: &land-area-type-0
        type: 0
        subType: 1
        name: 土块
        spendTimeInSecond: 15
        consumeEnergy: 3
        awardType:
          *award-type-list-0
#石土混合
    - total-list: [8,5,5,5,2]
      landAreaType: &land-area-type-1
        type: 0
        subType: 2
        name: 石土混合
        spendTimeInSecond: 25
        consumeEnergy: 5
        awardType:
          *award-type-list-0
#石块
    - total-list: [10,8,7,3,2]
      landAreaType: &land-area-type-2
        type: 0
        subType: 3
        name: 石块
        spendTimeInSecond: 20
        consumeEnergy: 4
        awardType:
          *award-type-list-0

#2.障碍######

#冒烟土地
    - total-list: [1,1,1,0,0]
      landAreaType: &land-area-type-3
        type: 1
        subType: 101
        name: 冒烟土地
        spendTimeInSecond: 0
        consumeEnergy: 0
        awardType:
          *award-type-list-0
#水洼
    - total-list: [1,1,1,1,0]
      landAreaType: &land-area-type-4
        type: 1
        subType: 102
        name: 水洼
        spendTimeInSecond: 0
        consumeEnergy: 0
        awardType:
          *award-type-list-0
#地底植物
    - total-list: [1,1,1,1,0]
      landAreaType: &land-area-type-5
        type: 1
        subType: 103
        name: 地底植物
        spendTimeInSecond: 0
        consumeEnergy: 0
        awardType:
          *award-type-list-0

#3.金币矿######

#一袋金币
    - total-list: [3,3,2,2,2]
      landAreaType: &land-area-type-6
        type: 2
        subType: 201
        name: 一袋金币
        spendTimeInSecond: 15
        consumeEnergy: 5
        awardType:
          *award-type-list-1
#一堆金币
    - total-list: [3,3,3,3,2]
      landAreaType: &land-area-type-7
        type: 2
        subType: 202
        name: 一堆金币
        spendTimeInSecond: 20
        consumeEnergy: 5
        awardType:
          *award-type-list-2
#一箱金币
    - total-list: [2,2,2,2,2]
      landAreaType: &land-area-type-8
        type: 2
        subType: 203
        name: 一箱金币
        spendTimeInSecond: 25
        consumeEnergy: 6
        awardType:
          *award-type-list-3

#3.钻石矿######

#一颗钻石
    - total-list: [2,5,7,5,3]
      landAreaType: &land-area-type-9
        type: 3
        subType: 301
        name: 一颗钻石
        spendTimeInSecond: 15
        consumeEnergy: 2
        awardType:
          *award-type-list-4
#一袋钻石
    - total-list: [0,2,10,17,19]
      landAreaType: &land-area-type-10
        type: 3
        subType: 302
        name: 一袋钻石
        spendTimeInSecond: 20
        consumeEnergy: 8
        awardType:
          *award-type-list-5
#蓝宝石矿
    - total-list: [0,0,0,3,11]
      landAreaType: &land-area-type-11
        type: 3
        subType: 303
        name: 蓝宝石矿
        spendTimeInSecond: 25
        consumeEnergy: 20
        awardType:
          *award-type-list-6
#4.无限币矿######

#一枚无限币
    - total-list: [3,3,3,3,3]
      landAreaType: &land-area-type-12
        type: 4
        subType: 401
        name: 一枚无限币
        spendTimeInSecond: 20
        consumeEnergy: 5
        awardType:
          *award-type-list-7
#紫水晶矿
    - total-list: [2,2,2,2,2]
      landAreaType: &land-area-type-13
        type: 4
        subType: 402
        name: 紫水晶矿
        spendTimeInSecond: 25
        consumeEnergy: 11
        awardType:
          *award-type-list-8

#VR币配置(单位:元,角),配置单位为角

#1.无限币上限######
  vr-coin-config:
    max: 210000000
#2.无限币掉落天数######
    base-day-count: 18250
#3.玩家基数######
    base-player-count: 800
#3.无限币开放开始时间######
    start-time: 1501430400000
#3.无限币随机配置######
#无限币小
    subtype-random-config:
      - [16,17,18,19,20]
#无限币大
      - [32,34,36,38,40]

#体力配置
#1.最大体力######
  energy-config:
    max: 100
#2.恢复单位体力所需时间(时间单位: 分钟)######
    time-in-second-increase-unit-energy: 3
#3.用户每天可购买体力最大值######
    user-day-buy-max-energy: 300


#设置每日体力(可设置多个时间段)######
  receive-energy-list:
    - num: 1
      startTime: '09:00:00'
      endTime: '11:00:00'
    - num: 2
      startTime: '15:00:00'
      endTime: '19:00:00'


