spring:
  data:
    mongodb:
      uri: mongodb://mine:123456@1.mongodb.db:22000,2.mongodb.db:22000,3.mongodb.db:22000/mine
  redis:
    cluster:
      nodes: redis.cloud.server1:6381,redis.cloud.server2:6381,redis.cloud.server3:6381,redis.cloud.server4:6382,redis.cloud.server5:6382,redis.cloud.server4:6382

application:
  vr-coin-redis-key: game-vr-coin-remain
  dubbo:
    applicationName: wxsk_vr_mine_game
    registryAddress: zookeeper://zookeeper.server1:2181?backup=zookeeper.server2:2181,zookeeper.server3:2181
    port: 60003

logging:
  config: classpath:log4j2.xml
